dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0 # Game engine
  socket_io_client: ^2.0.3 # Multiplayer
  provider: ^6.1.1 # State management
  shared_preferences: ^2.2.2 # Local data/settings
